.TH GITMULTIHOST 1 "2024/03/04" "1.0.1" "gitmultihost manual"
.SH NAME
gitmultihost \- A tool for handling git repositories with multiple SSH hosts.

.SH SYNOPSIS
.B gitmultihost
[\fI<git-command>\fR] [\fIarguments...\fR]

.SH DESCRIPTION
\fBgitmultihost\fR is a utility that facilitates managing git repositories with multiple SSH hosts. It integrates with the git command-line interface, allowing users to execute any git command. For commands that involve repository URLs, \fBgitmultihost\fR prompts the user to select an SSH host for the operation using \fBfzf\fR.

.SH OPTIONS
.TP
.BI \-h\ ,\ \-\-help
Show help message and exit.

.TP
.BI \-v\ ,\ \-\-version
Show version information and exit.

.SH EXAMPLES
.PP
Clone a repository using a selectable SSH host:
.RS
\fBgitmultihost clone git@github.com:user/repo.git\fR
.RE
.PP
Change the remote origin URL of a repository using a selectable SSH host:
.RS
\fBgitmultihost remote set-url origin git@github.com:user/repo.git\fR
.RE

.SH FILES
.TP
.B ~/.ssh/config
SSH configuration file used by \fBgitmultihost\fR to list available hosts.

.SH AUTHOR
.PP
Jean-Nicolas Boulay Desjardins

.SH REPORTING BUGS
.PP
GitHub repository: https://github.com/jnbdz/gitmultihost

.SH COPYRIGHT
.PP
This is open source software under the MIT license. See the LICENSE file for full license text.

.SH "SEE ALSO"
.PP
.B git(1),
.B ssh-config(5),
.B fzf(1)
